### ISSUE TITLE
Time to release the code.

### ISSUE THREAD

**Issue by codewithFlycat** [davidnvq/grit#1]
Hello, this is a good work. I read your paper  and wonder whether the code will be released or not and when ?
waiting for your ans.

**Comment by davidnvq** [comment]
Thanks for your interest!
Sorry that I am little busy this week for graduation stuff. I may release the code in next week. Please stay tuned.

**Comment by davidnvq** [comment]
Or maybe earlier on Friday..
I'll inform you here right after the update.

**Comment by codewithFlycat** [comment]
> 
Thanks for your reply!
Happy graduation!!!

**Comment by codewithFlycat** [comment]
> 
Thanks for your reply!
Happy graduation!!!

**Comment by codewithFlycat** [comment]
> 
Thanks for your reply!
Happy graduation!!!

**Comment by codewithFlycat** [comment]
> 
Thanks for your reply!
Happy graduation!!!

**Comment by verigle** [comment]
> 

today is friday, could you release the code?

**Comment by davidnvq** [comment]
Sorry that I couldn't make it until today as I need to revise my thesis for the submission.
I will be releasing the code tomorrow. Stay tuned for a while.

**Comment by davidnvq** [comment]
Noti: The initial version is released. It is not well-formatted yet and there may exist still some bugs (?). 
However, I decide to release for other people can try. I will go back to fix and clean the code later. Thanks.
