### ISSUE TITLE
can you give a example config and script for fast to train with freezed extractor?

### ISSUE THREAD

**Issue by verigle** [davidnvq/grit#10]
I try to training faster with freezed extractor, the error like this: 

```
omegaconf.errors.ConfigAttributeError: Key 'grid_stage' is not in struct
    full_key: model.grid_stage
    object_type=dict
```

```
omegaconf.errors.ConfigAttributeError: Key 'det_module' is not in struct
    full_key: model.detector.det_module
    object_type=dict
```

**Comment by davidnvq** [comment]
Hi there,
You can do this with simple training script as follows:
```shell
export DATA_ROOT=path/to/coco_dataset
# with pretrained object detector on 4 datasets
python train_caption.py exp.name=caption_4ds model.detector.checkpoint=4ds_detector_path \
optimizer.freezing_xe_epochs=10 \
optimizer.freezing_sc_epochs=10 \
optimizer.finetune_xe_epochs=0 \
optimizer.finetune_sc_epochs=0
```
It will train the model with the freezed detector rather than finetuning the entire model.

**Comment by davidnvq** [comment]
To be specific, it will first extract the pretrained region features and initial grid features, save them to HDF5 file.
During the training, the features will be loaded from this file rather than performing forward pass over the detector.
As I remember, it only consumes a few minutes per epoch for XE.

**Comment by verigle** [comment]
> Hi there, You can do this with simple training script as follows:
> 
> ```shell
> export DATA_ROOT=path/to/coco_dataset
> # with pretrained object detector on 4 datasets
> python train_caption.py exp.name=caption_4ds model.detector.checkpoint=4ds_detector_path \
> optimizer.freezing_xe_epochs=10 \
> optimizer.freezing_sc_epochs=10 \
> optimizer.finetune_xe_epochs=0 \
> optimizer.finetune_sc_epochs=0
> ```
> 
> It will train the model with the freezed detector rather than finetuning the entire model. You don't need to make any change in the `coco_config.yaml`. However, the final config would be saved with the according changes in the training script.

thank you for your repley
this script fail to runing with on change in the `coco_config.yaml`, the error will  appear  like this:
```
omegaconf.errors.ConfigAttributeError: Key 'grid_stage' is not in struct
    full_key: model.grid_stage
```
I found the code in extract_features.py near line 57:
```python
stage = config.model.grid_stage
```
the config of model.grid_stage can not find in coco_config.yaml

can you tell me the effect of config.model.grid_stage?

**Comment by davidnvq** [comment]
Ok, I got it..
Before that I ablated the layer/stage of Swin-base to extract the initial grid features. It was the last / the second last stage.
Then I decided to use only the last stage and removed the config to make it less messy. The last stage makes the model run faster while remaining similar performance.

> I found the code in extract_features.py near line 57:
Now, you can set the default `stage = -1`
Thanks for pointing out.

**Comment by verigle** [comment]
after set the default `stage = -1`, also fail to run the script  for fast to train with freezed extractor

the exception raise on  "grit/engine/caption_engine.py", line 330, in train_xe

    out = model(batch['samples'], batch['captions'])
KeyError: 'samples'

**Comment by davidnvq** [comment]
@verigle 

I am sorry for overlooking this error: `omegaconf.errors.ConfigAttributeError: Key 'det_module' is not in struct`.
* If you already fixed this above problem, extracting the features successfully (save it to `all_split.h5` file), you can uncomment line 103-104 in `train_caption.py` to save your time:
```python
        if getattr(config.optimizer, 'freeze_detector', False):
            for p, n in model.named_parameters():
                if 'detector' in n:
                    p.requires_grad = False
        # else:  <--- uncomment these 2 lines
        #    extract_vis_features(detector, config, device, rank)
```
    
If you haven't fixed the bug, please fix the config keynames in tools/extract_features.py as in [tools/extract_features.py # diff](https://github.com/davidnvq/grit/commit/ab491caec1db6aaf8ffa7ebd252d17fb8b8eec41#diff-caa4c3eec6f586705d26f689920e7694909d0d539cba063b73fa8cdfc5e5fbdc):
```python
# find the two lines:
                Q = config.model.detector.det_module.num_queries
                D = config.model.detector.det_module.reduced_dim
# replace by new keys:
                Q = config.model.detector.num_queries
                D = config.model.detector.d_model
```


For the error: `KeyError: 'samples'`, it requires you to modify the following files to make it work smoothly:
1. `datasets/caption/coco.py`
2. `datasets/caption/field.py`
3. `engine/caption_engine.py`
Check the commit difference (https://github.com/davidnvq/grit/commit/ab491caec1db6aaf8ffa7ebd252d17fb8b8eec41#diff-caa4c3eec6f586705d26f689920e7694909d0d539cba063b73fa8cdfc5e5fbdc) or pull the project again.

Thank you again for pointing out issues in the code base. I apologize for the inconvenience. I guarantee it works perfectly as I've just re-run it again. If you can't still make it work, feel free to inform me here.

**Comment by verigle** [comment]
thank you for your repley, now I can run the code.
