### ISSUE TITLE
Performance of Frozen detector

### ISSUE THREAD

**Issue by miasakachenmo** [davidnvq/grit#11]
Have you tested the performance of frozen detector? The training speed with detector is so slow for me to reproduce.

**Comment by miasakachenmo** [comment]
And what if the detector onle pretrain on coco dataset?

**Comment by davidnvq** [comment]
Thanks for interest.
> Have you tested the performance of frozen detector? The training speed with detector is so slow for me to reproduce.
Yes, we did. The performance is reported in the last row of this Table.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/30741785/186491137-bd9acd17-b199-48bd-9201-14b2c43b6694.png">

In Section Training (REAMDE), we described how to train the model with a freezed detector. It is allowed to extract the features into HDF5 files, speeding up significantly. 

Please try:
```shell
export DATA_ROOT=path/to/coco_dataset
# with pretrained object detector on 4 datasets
python train_caption.py exp.name=caption_4ds model.detector.checkpoint=4ds_detector_path \
optimizer.freezing_xe_epochs=10 \
optimizer.freezing_sc_epochs=10 \
optimizer.finetune_xe_epochs=0 \
optimizer.finetune_sc_epochs=0
```

> And what if the detector onle pretrain on coco dataset?

We haven't tested this.
