### ISSUE TITLE
The code without detector

### ISSUE THREAD

**Issue by tuyunbin** [davidnvq/grit#12]
Hi, Dr. Nguyen, thanks for your great work. I met a problem when reproducing your code. Because I have two 3090 GPUs with about 48GB memories, I cannot run this code. I'd like to know if without detector and only using grid features, how many gpu memories do I need?

**Comment by davidnvq** [comment]
Thank you for reporting. 
I believe that you can't run directly without change in the config. Its default setting is for 8 GPUs. With 2 GPUs, please change the config file (https://github.com/davidnvq/grit/blob/main/configs/caption/coco_config.yaml):
```yaml
  ngpus_per_node: 2 # 8
  world_size:  2 # 8
```
If it doesn't fit your GPU, please reduce  `batch_size`, too. 

> I'd like to know if without detector and only using grid features, how many gpu memories do I need?

Indeed, I can train it on a GPU of 24GB. If you need to freeze the pretrained detector, it will speed up significantly with extracted features by using the following script:
```shell
export DATA_ROOT=path/to/coco_dataset
# with pretrained object detector on 4 datasets
python train_caption.py exp.name=caption_4ds model.detector.checkpoint=4ds_detector_path \
optimizer.freezing_xe_epochs=10 \
optimizer.freezing_sc_epochs=10 \
optimizer.finetune_xe_epochs=0 \
optimizer.finetune_sc_epochs=0
```
It is noted that it may takes 40 minutes to extract the features. After that, the XE epoch will consume only a few minutes to train. SC epochs will take hours as it requires employing reinforcement learning.

**Comment by davidnvq** [comment]
> only using grid / region features

FYI, you can change to use `concatenated cross-attention`, in which only grid / region features are used in the config file
https://github.com/davidnvq/grit/blob/main/configs/caption/coco_config.yaml:
```yaml
defaults:
  - _self_
  - cap_generator@model.cap_generator: concat # <- set to concat
```

Then change `vis_inputs` accordining in https://github.com/davidnvq/grit/blob/main/configs/caption/cap_generator/concat.yaml:
```yaml
vis_inputs: ['gri'] # [gri], [reg], [gri, reg]
```

**Comment by Wangdanchunbufuz** [comment]
> Thank you for reporting. I believe that you can't run directly without change in the config. Its default setting is for 8 GPUs. With 2 GPUs, please change the config file (https://github.com/davidnvq/grit/blob/main/configs/caption/coco_config.yaml):
> 
> ```yaml
>   ngpus_per_node: 2 # 8
>   world_size:  2 # 8
> ```
> 
> If it doesn't fit your GPU, please reduce `batch_size`, too.
> 
> > I'd like to know if without detector and only using grid features, how many gpu memories do I need?
> 
> Indeed, I can train it on a GPU of 24GB. If you need to freeze the pretrained detector, it will speed up significantly with extracted features by using the following script:
> 
> ```shell
> export DATA_ROOT=path/to/coco_dataset
> # with pretrained object detector on 4 datasets
> python train_caption.py exp.name=caption_4ds model.detector.checkpoint=4ds_detector_path \
> optimizer.freezing_xe_epochs=10 \
> optimizer.freezing_sc_epochs=10 \
> optimizer.finetune_xe_epochs=0 \
> optimizer.finetune_sc_epochs=0
> ```
> 
> It is noted that it may takes 40 minutes to extract the features. After that, the XE epoch will consume only a few minutes to train. SC epochs will take hours as it requires employing reinforcement learning.

hello, if I want to train the freeze pretrained detector caption model on a single GPU,i should set the ngpus_per_node: 1;world_size:  1;Is this correct？Or what else do I need to set？I am looking forward to your reply！

**Comment by davidnvq** [comment]
That's correct. Also set the freeze_backbone and freeze_detector as I fixed the code. Please read `train_caption.py` to understand the logic of training ;)
For example:

```bash
export DATA_ROOT=path/to/coco_dataset
# with pretrained object detector on 4 datasets
python train_caption.py exp.name=caption_4ds model.detector.checkpoint=4ds_detector_path \
optimizer.finetune_xe_epochs=10 \
optimizer.finetune_sc_epochs=10 \ 
optimizer.freeze_backbone=True \ # Add this  
optimizer.freeze_detector=True \ # # Add this  
exp.ngpus_per_node=1 \ # Add this  
exp.world_size=1 \ # Add this  
```
