### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by hzf-hhh** [davidnvq/grit#2]
excuse me, May I ask you how long this model training will take？

**Comment by davidnvq** [comment]
Sorry for the late response. I was busy last week.
I will check the details of training tomorrow on the remote server and report you. Btw, I will release the code tomorrow.

**Comment by hzf-hhh** [comment]
thank you very much

**Comment by davidnvq** [comment]
It takes for 38 minutes for 1 XE epoch and 52 minutes for 1 RL epoch on 8 GPU A100 in DDP mode.
