### ISSUE TITLE
the data sets

### ISSUE THREAD

**Issue by bai-24** [davidnvq/grit#25]
Dear Author, Can you share the four data sets after consolidation(i.e., Visual Genome (VG),COCO, OpenImages, and Objects365)

**Comment by davidnvq** [comment]
Basically, you only need to download each dataset and store them separately.
What do you mean by "after consolidation"?
The `ConcatDataset` is all you need for this purpose:
https://github.com/davidnvq/grit/blob/main/datasets/detection/__init__.py
