### ISSUE TITLE
L in extract_features.py 

### ISSUE THREAD

**Issue by messithanh2k** [davidnvq/grit#27]
Dear authors,
I extract feature and save into HDF5 file but number of img_ids don't equal number of reg_feat and gri_feat. 
In extract_features.py, 
Why does batch_size in Dataloader equal BATCH_SIZE - 1 and  why append random tensor to imgs from batch in dataloader.
Thank authors.

**Comment by messithanh2k** [comment]
I have done it.

**Comment by davidnvq** [comment]
It is nice that you resolved things yourself. For more detail, let me assure as follows.

1. `L` is the total number of images in the (COCO) dataset.

> Why does batch_size in Dataloader equal BATCH_SIZE - 1 and why append random tensor to imgs from batch in dataloader

2. Adding a random tensor of a **FIXED SHAPE** `HxW` is a small trick to ensure all the images in the dataset would be resized to the same `HxW` size. It is for the purpose of saving tensors of the same shape into HDF5. 
* images will be resized to the maximum shape `HxW` as in https://github.com/davidnvq/grit/blob/a47e3629295c83254bf828ee3840ae3983cdf0ea/models/caption/detector.py#L44
* More about resizing the input images can be found in 
https://github.com/davidnvq/grit/blob/a47e3629295c83254bf828ee3840ae3983cdf0ea/utils/misc.py#L327

* `Deformable Attention` prefers the input batch of size 2^N (e.g., 64). Therefore, to make sure that the total number of input images (including the random tensor) = BATCH_SIZE = 64, the real images fetched from the dataloader should be `batch_size = BATCH_SIZE - 1`, in which `1` is for the random tensor ;)
