### ISSUE TITLE
where can I find the function where name like "extract_vis_features"

### ISSUE THREAD

**Issue by verigle** [davidnvq/grit#3]
```
from tools.extract_features import extract_vis_features
```

could not find function "extract_vis_features“ in extract_features.py

**Comment by davidnvq** [comment]
Sorry for the mismatch after refactoring the name of function. It is indeed `extract_gri_features`. 
Thanks for notifying the error, let me fix this.

**Comment by davidnvq** [comment]
I made a commit to change `extract_gri_features` into `extract_vis_features` accordingly.
