### ISSUE TITLE
Missing detection dataset

### ISSUE THREAD

**Issue by Huy0812** [davidnvq/grit#32]
Dear author. The object detector missing some important files for training in train_config.yaml. Can you provide those files ! Thanks
`
 ${oc.env:DATA_ROOT}/vg/annotations/train_ann_lmdb
 ${oc.env:HOME}/datasets/vg/annotations/train_objects.json
 ${oc.env:HOME}/datasets/vg/annotations/attribute2ind.json
 ${oc.env:HOME}/datasets/vg/annotations/oid2attr.json
`

**Comment by davidnvq** [comment]
Thanks for interest. I'm sorry for the late response.

In fact, the configuration files are for training object detection.
Do you still need them?

**Comment by Huy0812** [comment]
Thanks for respond
Yes, I need it. I training object detection with new backbone

**Comment by davidnvq** [comment]
Here you go. Please download them quickly as I may not maintain it on GG drive.
https://drive.google.com/file/d/1gcP9kMz51erRqt_nLYKqFAOs89dfeQPk/view?usp=share_link

**Comment by Huy0812** [comment]
Thanks for help !!!
Can you provide 
 `${oc.env:HOME}/datasets/vg/annotations/test_objects.json  ${oc.env:HOME}/datasets/vg/annotations/test_coco.pkl  ${oc.env:HOME}/datasets/vg/annotations/val_objects.json  ${oc.env:HOME}/datasets/vg/annotations/val_coco.pkl `

Sorry for not mentioning it soon. Thanks

**Comment by davidnvq** [comment]
No worries. Please download from this link: 
https://drive.google.com/file/d/14bA-Ou9T9D0jnlgr_-d_jRaSJtDklJzy/view?usp=share_link
