### ISSUE TITLE
Grid Feature Network

### ISSUE THREAD

**Issue by Huy0812** [davidnvq/grit#33]
Dear Author, 
I read the paper and don't understand how Grid Feature Network works. You said: "We intend to extract contextual information hidden in the input image by modeling the spatial interaction between the grid features". That means it uses  scene graph. If not how you can extract contextual information ?  Thanks

**Comment by davidnvq** [comment]
It is not necessary that contextual information must be extracted from scene graph.
Indeed, we assume that "contextual information" here can be learned through the training of image captioning task. It is the learned grid features (the outputs of the grid feature network).
