### ISSUE TITLE
The Visual Genome dataset

### ISSUE THREAD

**Issue by bai-24** [davidnvq/grit#38]
Dear Author,
The Visual Genome dataset I downloaded was not partitioned. How to divide the Visual Genome dataset into training, testing, and validation sets?How to form the annotations folder?

**Comment by quangvnai** [comment]
You can find the splits here.
https://github.com/peteanderson80/bottom-up-attention/tree/master/data/genome

I also converted them into the json files according to COCO annotation format.
Feel free to download them (including the notebook) from here:
https://drive.google.com/drive/folders/1c7eWTjrlo_UJuKH3GwHIvTYMwzTkbIRd?usp=sharing

**Comment by bai-24** [comment]
Thank you.But there are many files in vg_train.yaml, vg_val.yaml, vg_test.yaml and coco_val.yaml that I don't know how to generate. Can you provide them?

**Comment by quangvnai** [comment]
Can you check here?
https://github.com/davidnvq/grit/tree/main/configs/detection/datasets

**Comment by bai-24** [comment]
train_ann_lmdb, train_objects.json, vgcocooiobjects_v1_class2ind.json, attribute2ind.json, oid2attr.json in vg_train.yaml. val_objects.json, val_coco.pkl in vg_val.yaml. test_objects.json, test_coco.pkl in vg_test.yaml. anno_1848_val2017.json, coco_vgoiv6_class2ind.json in coco_val.yaml.

**Comment by quangvnai** [comment]
@bai-24 Sorry for late reply. 
You can download all here: https://drive.google.com/drive/folders/1c7eWTjrlo_UJuKH3GwHIvTYMwzTkbIRd?usp=share_link

In fact, you don't need train_ann_lmdb. Please find the corresponding place in Dataset code to turn off the need of this file.
