### ISSUE TITLE
Replacement for MSDeformAttn?

### ISSUE THREAD

**Issue by shayanjoya** [davidnvq/grit#7]
Hi, thanks for your work!
is there a drop is replacement in pure pytorch for MSDeformAttn which we can use instead, or an alternative you can recommend? since it is not implemented for CPU usage.

**Comment by davidnvq** [comment]
Thanks for your interest.
I haven't tried the CPU-based implementation but I found a similar issue, which points out the author's implementation for debugging:
https://github.com/fundamentalvision/Deformable-DETR/issues/131
Should you try it.
