### ISSUE TITLE
Inference on new images using pretrained model

### ISSUE THREAD

**Issue by bt-ngo** [davidnvq/grit#8]
I'd like to ask how to generate caption for new images using pretrained model. There seems to be evaluation code only. Thank you and have a great day!

**Comment by davidnvq** [comment]
Thanks for interest. 
I'll create a Jupyter notebook for this purpose. 
I will notify you here soon (within 1-2 days)?

**Comment by davidnvq** [comment]
@bt-ngo 
I have just added the inference code. Please feel free to try.
https://github.com/davidnvq/grit#inference-on-rgb-image

**Comment by eslambakr** [comment]
Thank you very much for your keen efforts @davidnvq .
I tried to run your inference code; "inference_caption.py" but unfortunately, I got <unk> despite the model is loaded correctly without any errors.

Your help is much appreciated!
Thanks in advance!

**Comment by eslambakr** [comment]
I solved the issue by upgrading the Cuda and Pytorch version to match the versions mentioned in the readme.
No it works perfectly!
Thank you very much for sharing your amazing work and the source code!
