### ISSUE TITLE
Train your own coco format data

### ISSUE THREAD

**Issue by 1272203655** [davidnvq/grit#9]
Hi, this is really a great job!
I want to train my own dataset now, but have some questions like how to generate the vocab.json, can you give the exact script to process the dataset, if so, I'd appreciate it!

**Comment by davidnvq** [comment]
I think the `vocab.json` contains sufficient words for general image captioning datasets.
Is your dataset domain different **too much** from COCO datasets?

**Comment by 1272203655** [comment]
I would like to train a Chinese dataset.

**Comment by davidnvq** [comment]
I'm not familiar with `tokenization` in Chinese.
Suppose that it is similar to the English tokenizer, use can obtain a `vocab.json` file by:

```python
from datasets.caption.field import TextField

text_field = TextField(vocab_path="path_to_save_vocab.json", build_vocab=True)

# given a list of captions
source = [
"This is a first caption",
"This is a second caption",
....
]

text_field.build_vocab(source)
```

That's how it works.

**Comment by 1272203655** [comment]
yes, thank you very much!

**Comment by davidnvq** [comment]
You just need to extract the Chinese caption,  create a file `make_vocab.py`, and run it.
However, I believe that there should be a different way to tokenizing Chinese characters. You may investigate yourself :)

**Comment by davidnvq** [comment]
If you have any question, feel free to raise a new issue.

**Comment by optas** [comment]
Hi, related to this, two questions:

1) in the config: for model.max_len shall we put the maximum len of any (tokenized) utterance in the dataset, or the that len + 2 to count for (<bos> and <eos>)?

2) you seem to be using the spacy tokenizer, but instead of having the parameter "tokenize" of TextField active, you have hardwired the tokenizer in the code (TextField class, Line 109). Why? Is there any good reason?

Thanks,

**Comment by yan1617262965** [comment]
> 我不熟悉中文。假设它类似于英文分词器，使用 可以通过以下方式获取文件：`tokenization``vocab.json`
> 
> ```python
> from datasets.caption.field import TextField
> 
> text_field = TextField(vocab_path="path_to_save_vocab.json", build_vocab=True)
> 
> # given a list of captions
> source = [
> "This is a first caption",
> "This is a second caption",
> ....
> ]
> 
> text_field.build_vocab(source)
> ```
> 
> 这就是它的工作原理。

Hello author, according to your example, the vocab.json file I generated contains "freqs" and "itos", but I cannot obtain "stoi". May I ask if you could tell me why? Or is there no need for 'stoi' participation in GRIT training



I would greatly appreciate it if you could reply to me as soon as possible
